[supervisord]
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log

[program:schedule]
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
stderr_logfile=/var/log/schedule.err.log
stdout_logfile=/var/log/schedule.out.log
